# ATAC-seq analysis configuration

# Sample information table
samples_table: "ref/samples.csv"


# Reference genome index for bowtie2
hisat2_index: "ref/ENSEMBL/genome"

# Blacklist regions file
blacklist: "ref/hg38_blacklist_regions.bed"
effective_genome_size: 2913022398
